### ISSUE TITLE
Portals build problem with system installed libfabric

### ISSUE THREAD

**Issue by jhrobichaux** [Sandia-OpenSHMEM/SOS#103]
When trying to build Portal4 transport on a system running CentOS Linux release 7.1.150, which has libfabric v1.1.1 installed by default, problems are encountered with trying to build the various 'osh*' commands. It appears that the configure script identifies libfabric is installed on the system and somehow tries to support both (see output of Transport stanza). However, in the resulting config.h only the OFI/libfabric  macros are defined.  

I am able to work around this by running configure with '--without-ofi', however wanted to bring this feature to your attention. 

Below are the salient output from the output of the original configure command, and make. Let me know if need more information. 

=== Config Errors ===
./configure --with-portals4=$BASE/portals4/  --disable-long-fortran-header --prefix=$BASE/sandia-shmem-portals4 \
 --enable-error-checking --enable-remote-virtual-addressing --enable-picky \
 --enable-pmi-simple FCFLAGS="-fcray-pointer" \
 CC='gcc' CFLAGS='-g -O0'

...
Looking for library in lib
checking for PtlLEAppend in -lportals... yes
checking --with-ofi value... simple ok (unspecified)
checking --with-ofi-libdir value... simple ok (unspecified)
checking rdma/fabric.h usability... yes
checking rdma/fabric.h presence... yes
checking for rdma/fabric.h... yes
looking for library without search path
checking for fi_getinfo in -lfabric... yes
...

Transports:
  **Portals 4:      yes**
  **OFI:            yes**
  XPMEM:          no
  CMA:            no
...

=== Make Errors ===
...
cp ./shmem_launcher_script.in oshrun
  CC       transport_portals4.lo
  SED      oshcc
  SED      oshc++
  SED      oshCC
  SED      oshfort
  CC       shmem_free_list.lo
  CC       runtime-pmi.lo
  CC       malloc.lo
  CC       init.lo
  CC       collectives.lo
  CC       init_c.lo
In file included from collectives.c:21:0:
shmem_internal_op.h: In function ‘shmem_internal_reduce_local’:
config.h:20:21: error: ‘FI_INT16’ undeclared (first use in this function)
 #define DTYPE_SHORT FI_INT16
                  ^
...

**Comment by jdinan** [comment]
Thanks for the bug report.

It looks like we need to not enable OFI if the user has explicitly enabled Portals.  Presently, we don't support building for both at the same time.  We should also flag an error if we reach then end of the configuration and both are enabled, since it will cause a build failure.

**Comment by jdinan** [comment]
@davidozog Has this issued been fixed?

**Comment by davidozog** [comment]
Yes, I'm pretty certain this was closed with #328.  Our solution was to raise an error at configure time if users try to enable both OFI and Portals.
