### ISSUE TITLE
A locking problem

### ISSUE THREAD

**Issue by ryancaicse** [Sandia-OpenSHMEM/SOS#1052]
Hi, lock shmem_internal_mutex_ptl4_ctx is not released before 306, although it could be rare to happen. Should it be a bug?
https://github.com/Sandia-OpenSHMEM/SOS/blob/871e4e232077c57cfd2677e947a351018da651a5/src/transport_portals4.c#L281-L323

**Comment by wrrobin** [comment]
@ryancaicse Thanks for catching it. That is a bug.

**Comment by wrrobin** [comment]
Closed by #1054
