### ISSUE TITLE
Symbol hiding macros for internal variables / functions

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Sandia-OpenSHMEM/SOS#12]
```
Currently, all non-static internal symbols are named shmem_internal_*, but are 
public functions in the sma library.  They should really be marked as private 
on linkers that support public/private function marking.

```

Original issue reported on code.google.com by `bwbarrett@gmail.com` on 21 Nov 2013 at 1:41

**Comment by jdinan** [comment]
Detect __attribute__ support: https://www.gnu.org/software/autoconf-archive/ax_gcc_func_attribute.html

```
#if HAVE_ATTRIBUTE_VISIBILITY
#define SOS_INTERNAL_FCN __attribute__((visibility("internal")))
#else
#define SOS_INTERNAL_FCN
#endif

void SOS_INTERNAL_FCN shmem_internal_...()
{
   ...
}
```

**Comment by jdinan** [comment]
Although, I'm tempted to crib ```OPAL_CHECK_VISIBILITY``` and ```OPAL_CHECK_ATTRIBUTES``` from OpenMPI.  It seems easier to mark public API functions as visible (OpenMPI approach) rather than to mark internal API functions as not visible (what I mentioned above).
