### ISSUE TITLE
alltoall test using invalid stride

### ISSUE THREAD

**Issue by jeffhammond** [Sandia-OpenSHMEM/SOS#125]
Where in the OpenSHMEM spec does it say that this is legal?

https://github.com/Sandia-OpenSHMEM/SOS/blob/v1.3.0-dev/test/unit/alltoall.c#L65

Thanks.

**Comment by jdinan** [comment]
When there is only 1 PE in the active set, it contains only the starting PE, which the user provides through the PE_start argument.  Therefore, the value provided in the stride argument is irrelevant.  This is not stated explicitly in the spec, but I think this is a reasonable conclusion for active sets containing 1 PE.
