### ISSUE TITLE
Collectives Unit Tests: Coverage over PE active sets

### ISSUE THREAD

**Issue by kseager** [Sandia-OpenSHMEM/SOS#126]
## Issue

Presently, there is sparse coverage over PE active sets (start, stride, size arguments) in the test suite.

In particular, the case where `PE_size == 1` may not be handled correctly in all collectives, and should be tested.
## To Do
1. Review tests to determine what is already covered.
2. Identify test cases for active sets, e.g. all PEs, only one PE, odd PEs, even PEs, etc
3. Ensure that active sets are covered for all collectives.

**Comment by jdinan** [comment]
Boy, this was a good issue.  Should be in better shape now that we are running the Cray tests and added tests in other recent commits.
