### ISSUE TITLE
External component locations (e.g. PMI) not passed to wrappers

### ISSUE THREAD

**Issue by tonycurtis** [Sandia-OpenSHMEM/SOS#138]
My configure stanza passes LDFLAGS settings (-L and -rpath) for the location of libfabric and PMI libraries.

These don't get passed on to oshcc and friends, meaning use of LD_LIBRARY_PATH in my login environment required to find these libraries at execution time (I am allergic to LD_LIBRARY_PATH).

**Comment by hppritcha** [comment]
this is an annoying thing.  taking this issue.

**Comment by jdinan** [comment]
@davidozog Can we close this issue?

**Comment by davidozog** [comment]
@jdinan Yes, I'd say so.

**Comment by jdinan** [comment]
Fixed in #327
