### ISSUE TITLE
FI Version in getinfo query

### ISSUE THREAD

**Issue by jdinan** [Sandia-OpenSHMEM/SOS#149]
The OFI manpages recommend a hard-coded API version in the call to ```fi_getinfo```, but we have:

```
    ret = fi_getinfo( FI_VERSION(OFI_MAJOR_VERSION, OFI_MINOR_VERSION),
                      iface_addr, svc_name, 0, &hints, p_info);
```

Should this be changed for forward compatibility?

**Comment by sayantansur** [comment]
This is hardcoded, right? OFI_MAJOR_VERSION is defined by SOS at compile time.

**Comment by jdinan** [comment]
If the application is designed to work with a specific version of libfabric, shouldn't we give that version number in fi_getinfo rather than using the version number of the libfabric instance the application is currently being compiled with?  There could have been a change (e.g. from 1.x to 2.x) that broke backward compatibility without changing the API.  The application could depend on 1.x or 2.x and if the wrong version is being used to compile you won't get an error.

**Comment by sayantansur** [comment]
You're right, but in this case SOS is designed to work with libfabric version 1,0. You are passing this into getinfo(). The macros OFI_MAJOR_VERSION, OFI_MINOR_VERSION are defined in src/transport_ofi.c, defined by SOS, not OFI. I think the naming of these macros is confusing.

**Comment by jdinan** [comment]
Oh, :facepalm:.  Yeah, I had assumed that the MAJOR/MINOR macros are being defined by libfabric.
