### ISSUE TITLE
SMA_INFO transport specific options

### ISSUE THREAD

**Issue by kseager** [Sandia-OpenSHMEM/SOS#176]
### Issue

Environment variables like SMA_OFI_ATOMIC_CHECKS_WARN, are specific to the OFI transport and need to be exposed in a transport specific fashion

### Solution 

Refactor SMA_INFO such that it follows suite to the transport independent interface and transport specific aspects are encapsulated by their respective implementation

**Comment by jdinan** [comment]
Specifically, add a function ```void shmem_transport_print_info(void)``` that can be called when SMA_INFO is handled to print info output from the transport.

**Comment by jdinan** [comment]
Closed by #205.
