### ISSUE TITLE
Missing SHMEM_ALLTOALLS_SYNC_SIZE const

### ISSUE THREAD

**Issue by naveen-rn** [Sandia-OpenSHMEM/SOS#186]
pSync const usage in 

./test/unit/alltoalls.c:long pSync[SHMEM_ALLTOALL_SYNC_SIZE];
./test/unit/alltoalls.c:    for (i = 0; i < SHMEM_ALLTOALL_SYNC_SIZE; i++)

should be SHMEM_ALLTOALLS_SYNC_SIZE. And, a quick search on SHMEM_ALLTOALLS_SYNC_SIZE ends up empty, I suppose SHMEM_ALLTOALLS_SYNC_SIZE constant for shmem_alltoalls operations is missing.

**Comment by jdinan** [comment]
Thanks for the bug report!
