### ISSUE TITLE
Error Queue

### ISSUE THREAD

**Issue by kseager** [Sandia-OpenSHMEM/SOS#189]
### Issue

Right way to handle error handling for counter_wait, need to follow-up with OFI recommended pathway
referenced by PR #183
### Solution Ideas

Jim's proposal: 
The other way to solve this is to check the error count on event counter. This is what's done in the Portals transport, but it looks like we missed it in the OFI implementation of quiet. Given that we have the CQ anyway, it's always nice to print an error message (all we know from the counter is that an error occurred, not what caused it). You might want to add a comment about the event counter approach, for future performance tuning in case binding the the CQ to the EP has a performance impact for some provider.

**Comment by jdinan** [comment]
Resolved by #526 and #528
