### ISSUE TITLE
char versions of shmem_iput, shmem_iget

### ISSUE THREAD

**Issue by jpdoyle** [Sandia-OpenSHMEM/SOS#197]
The C11 bindings in shmem.h refer to shmem_char_iput (https://github.com/Sandia-OpenSHMEM/SOS/blob/master/mpp/shmem.h.in#L525) and shmem_char_iget (https://github.com/Sandia-OpenSHMEM/SOS/blob/master/mpp/shmem.h.in#L562), but they don't seem to be declared or implemented. This looks like an implementation gap -- OpenSHMEM 1.3 includes iput/iget for all RMA types.

**Comment by jdinan** [comment]
Fixed.
