### ISSUE TITLE
XPMEM put/get __sync_synchornize

### ISSUE THREAD

**Issue by kseager** [Sandia-OpenSHMEM/SOS#200]
## Issue

extra synchronization around a memcpy should not be needed; quiet should instead be the point of using the memory fence to ensure the change is visible to other cores

ref:
http://pgas11.rice.edu/papers/BrightwellPedretti-OpenSHMEM-PGAS11.pdf
## Proposed solution

1) add ifdef syncs with TOTAL_DATA_ORDERING, including NO-OP fence
2) verify that shmem_wait calls have XPMEM syncs

**Comment by jdinan** [comment]
Related to #452

**Comment by jdinan** [comment]
Can't remove memory barriers until internal wait/wait_until calls contain appropriate memory barriers.
