### ISSUE TITLE
Optimize quiet/fence

### ISSUE THREAD

**Issue by jdinan** [Sandia-OpenSHMEM/SOS#202]
The OpenSHMEM quiet operation must wait for remote completion of all pending blocking and nonblocking operations, whereas the fence operations must only ensure ordering of remote updates.  Currently, SOS waits for completion of all pending communication in both quiet and fence operations.  In the future, we plan to leverage the separation of read and write counters to optimize these operations.  In this model, the quiet operation waits for completion of both remote writes and reads, whereas the fence operation waits only for completion of remote writes.

**Comment by jeffhammond** [comment]
The other optimization of fence is to enforce ordering of RMA such that fence is a no-op, which is free on *some* networks.  I think I did this in OSHMPI.  Or I didn't, but I at least thought about it 😆

**Comment by jdinan** [comment]
There is a total ordering configure option that enables this optimization, but see #129.
