### ISSUE TITLE
Relation between SHMEM_VENDOR_STRING and shmem_info_get_name

### ISSUE THREAD

**Issue by naveen-rn** [Sandia-OpenSHMEM/SOS#249]
It looks like that in test: shmem_info_f.f90 , the SHMEM_VENDOR_STRING library constant is being compared to the string obtained from shmem_info_get_name 

> if (lib_name .ne. SHMEM_VENDOR_STRING) then

I suppose this is a SOS specific check...because the OpenSHMEM standard doesn't expect this condition. The standard insists only on the MAJOR and MINOR version constants to be same as shmem_info_get_version. Let me know, if this is correct. 

Also the print statements need a minor change, from

> print *, me, "SHMEM_VENDOR_STRING: ", lib_name

to

> print *, me, "SHMEM_VENDOR_STRING: ", SHMEM_VENDOR_STRING

**Comment by jdinan** [comment]
Yes, the equivalence is SOS-specific, not required by the OpenSHMEM standard.  Fortran strings in C are odd and I wanted a way to check that the bindings work correctly.

Thanks for the bugfix!

**Comment by naveen-rn** [comment]
Thanks for clarification, if possible please a little note as comment.
