### ISSUE TITLE
Optimize cntr_wait behavior

### ISSUE THREAD

**Issue by kseager** [Sandia-OpenSHMEM/SOS#284]
SHMEM-OFI currently asks cntr_wait to block without a wait object. This is a bug caught by the gni provider and we currently do not pass tests on this provider as a result: 
https://github.com/ofi-cray/libfabric-cray/issues/1038#issuecomment-265783399

Fix:

1) (Fixed by #290)  set fi_wait_object to type FI_WAIT_UNSPEC
2) (Not yet addressed) since cntr_wait is expensive, mix cntr_read/cntr_wait usage
while(under spin threshold) {cntr_read}
if still not at threshold, block on fi_cntr_wait

**Comment by jdinan** [comment]
Close by #398
