### ISSUE TITLE
Contexts improvements

### ISSUE THREAD

**Issue by jpdoyle** [Sandia-OpenSHMEM/SOS#296]
- [x] OFI is initialized in thread-safe mode, but there are still mutexes on domains 
   - [x] Incrementing pending_count in contexts in a thread-safe way requires using an atomic increment operation (DONE)
 - [x] The contexts-focused performance tests need to be formatted to have the same init/finalize structure as the other performance tests (I don't remember the specifics from the notes I have, but @kseager mentioned this issue)
 - [x] Make SHMEMX_CTX_DEFAULT and SHMEMX_DOMAIN_DEFAULT valid before shmem_init()
    - [x] Currently, they are both initialized in shmem_init, so a global variable initialized to SHMEMX_CTX_DEFAULT is invalid
    - [x] They are both declared extern in shmemx.h, and properly declared in transport_ofi.c
    - [x] shmemx_domain_create takes a shmemx_domain_t* (shmemx_domain_t is a void* for a shmem_transport_dom_t)
      - [x] If you split shmemx_domain_create into an allocation step and a separate function for initialization, you can initialize the globally-allocated shmem_transport_dom_t in shmem_init()

**Comment by jdinan** [comment]
@davidozog Readme.  :)
