### ISSUE TITLE
SMA_REDUCE_ALGORITHM=recdbl error

### ISSUE THREAD

**Issue by davidozog** [Sandia-OpenSHMEM/SOS#326]
The Cray reduction tests occasionally result in incorrect buffers when SMA_REDUCE_ALGORITHM=recdbl. For example, [this program](https://github.com/openshmem-org/tests-cray/blob/master/sma1/all_and_int_ext.c).

Some observations:

- I can reproduce this bug with 3 PEs or more on my laptop.
- The error is non-deterministic, with a higher rate of failure with more PEs.
- The test iterates over all reasonable values for (`PE_start, logPE_stride,` and `PE_Size`).  For a given number of PEs at launch, failures occur _consistently_ for various 3-tuple values.  For example, with (`PE_start=2, logPE_stride=0, PE_size=2`), and SHMEM_N_PES=4, failure rate is quite high, but so far there are zero failures for other configurations, such as (1, 0, 3).

**Comment by jdinan** [comment]
This will be an error in the newer ```shmem_internal_op_to_all_recdbl_sw``` collective that we fall back on when the provider doesn't have atomic support.  I don't think we have been thorough about testing the active set arguments with this routine.  That's the first place I would look.
