### ISSUE TITLE
Remove --with-ofi build flag

### ISSUE THREAD

**Issue by davidozog** [Sandia-OpenSHMEM/SOS#328]
The `--with-ofi` and `--with-ofi-libdir` flags are now deprecated, but they're still supported so as to not annoy those who depend on them.  When the time is right, these flags should be removed for the favored (and upstream) `--with-libfabric` and `--with-libfabric-libdir` from OPAL.

**Comment by jdinan** [comment]
Since we removed the subconfigure for shmem_pmi, autoconf will generate a warning after we remove --with-ofi.  I suggest we remove it in 1.3.3.

**Comment by jdinan** [comment]
@davidozog Can we close this issue?

**Comment by davidozog** [comment]
Yes.  It was resolved with #390.  Now we should use --with-ofi and ***not*** --with-libfabric, though both do the same thing.
