### ISSUE TITLE
Add --with-oshrun-launcher=... option

### ISSUE THREAD

**Issue by jdinan** [Sandia-OpenSHMEM/SOS#368]
Add a ```--with-oshrun-launcher=...``` configure option so users don't have to rely on a path search to find the launcher.

First, update ```src/shmem_launcher_script.in``` to be generated by autoconf.  This could be a pain, since it's already an automake generator input.  We may want to rename this to something like ```src/shmem_laincher_script.sed.in``` and let autoconf hack off the ```.in``` and substitute the value for ```SEARCH_LAUNCHERS```.  Sed then hacks off the ```.sed``` to generate oshrun.

**Comment by jdinan** [comment]
Ref: #113

**Comment by richardnorth3** [comment]
What about the $OSHRUN_LAUNCHER environment variable that users can set? Or would the configure option be more useful/preferential?

**Comment by jdinan** [comment]
I would implement this but having autoconf substitute the ```SEARCH_LAUNCHERS``` variable in ```shmem_launcher_script.in```.

**Comment by richardnorth3** [comment]
Should we support any launcher the user sets that is not in the list of launchers? Or even not in their `PATH`?

**Comment by jdinan** [comment]
We should blindly use whatever the user supplies, regardless of whether it's available on the system where SOS is being compiled.

**Comment by jdinan** [comment]
Close by #420
