### ISSUE TITLE
GUPS fails with certain npes and memory sizes

### ISSUE THREAD

**Issue by davidozog** [Sandia-OpenSHMEM/SOS#384]
GUPS seg. faults when launching certain numbers of PEs (for example, 5, 14, ..., 166, and more) on the 3 providers I've tried so far (libfabric/psm2, libfabric/sockets, portals4/IB).

The smallest job that consistently produces the error is this:

```
oshrun -n 5 ./gups -m 205
```

With 5 PEs, I also notice that all buffer sizes below 204 bytes work fine, and all above 204 seg. fault.

The error over portals4 on IB is:
```
[001] ERROR: ../../src/transport_portals4.h:855 return code 5
[mpiexec@comet-14-04.sdsc.edu] handle_pmi_cmd (pm/pmiserv/pmiserv_cb.c:52): Unrecognized PMI command: abort | cleaning up processes
[mpiexec@comet-14-04.sdsc.edu] control_cb (pm/pmiserv/pmiserv_cb.c:280): unable to process PMI command
[mpiexec@comet-14-04.sdsc.edu] HYDT_dmxu_poll_wait_for_event (tools/demux/demux_poll.c:76): callback returned error status
[mpiexec@comet-14-04.sdsc.edu] HYD_pmci_wait_for_completion (pm/pmiserv/pmiserv_pmci.c:198): error waiting for event
[mpiexec@comet-14-04.sdsc.edu] main (ui/mpich/mpiexec.c:344): process manager error waiting for completion

```

Over libfabric the error is only:
```
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   PID 92899 RUNNING AT node109
=   EXIT CODE: 11
```

**Comment by jdinan** [comment]
The Portals 4 PMI command is a bit weird because the PMI version included with Portals 4 doesn't properly support the abort command (we have since fixed this in SOS).  It might be useful to see why abort was called.  When you build Portals, you can give ```--disable-pmi-from-portals``` and then ```--enable-pmi-simple``` on the SOS build.
