### ISSUE TITLE
openmpi launcher support

### ISSUE THREAD

**Issue by kseager** [Sandia-OpenSHMEM/SOS#416]
We currently do not have OpenMPI mpiexec/mpirun compatibility.

known issues:
During a make check ipgm/shrealloc will fail.

It appears also that the rank assignment cannot be trusted in this environment
mpirun -n 2 ./hello
Hello World from 0 of 1
Hello World from 0 of 1

solution:
Probably need orte support via configure to plug into libopen-rte.so (cannot rely on pmi-simple).

**Comment by jdinan** [comment]
Better solution is PMIx support, which should cover interoperability with a
number of process managers.

**Comment by davidozog** [comment]
Good call, Jim!  Angela and I seem pretty close to having PMIx prototype support (at least via the "PMI-1 compatibility interface"), but we're currently having some linking challenges.

**Comment by jdinan** [comment]
#443 Adds PMIx support

**Comment by jdinan** [comment]
PMIx support merged and that's the direction OpenMPI is headed, so I'm going to mark this as resolved.
