### ISSUE TITLE
Update Documentation

### ISSUE THREAD

**Issue by jdinan** [Sandia-OpenSHMEM/SOS#42]
The README file is stale and needs some updates, including:

1. [x] Update project name to Sandia OpenSHMEM
2. [x] Update build instructions for OFI
3. [x] Update build instructions for PMI
4. [x] Update running instructions for PMI
5. [x] Update testing instructions to document TEST_RUNNER and NPROCS make variables
6. [x] Review LICENSE file to ensure it is current
7. [x] Do we want to add a contributors file?
8. [x] Update NEWS file, following GNU NEWS formatting guidelines
9. [x] Update version information to 1.2.0
10. [x] Update Fortran bindings info to describe long/short header option

**Comment by jdinan** [comment]
@regrant, there's one item left for you.  :)

**Comment by regrant** [comment]
Licensing should now be good.
