### ISSUE TITLE
OpenSHMEM 1.4 - change log #3 - init() must match finalize()

### ISSUE THREAD

**Issue by davidozog** [Sandia-OpenSHMEM/SOS#446]
Check that shmem_init must be matched with a call to shmem_finalize.

**Comment by jdinan** [comment]
Check that {shmem_init[_thread], start_pes} X {shmem_finalize, implicit finalize} combinations are handled correctly.

**Comment by wrrobin** [comment]
@jdinan In the case of no shmem_finalize in the code, should a WARN be enough or should we have some build step to detect that?

**Comment by wrrobin** [comment]
@jdinan This looks good to me if a warning is desired in case of a mismatch.  
shmem_init without finalize => generates the warning
shmem_init_thread without finalize => generates the warning
start_pes without finalize => does not generate warning
