### ISSUE TITLE
OpenSHMEM 1.4 - change log #6 - remove volatile

### ISSUE THREAD

**Issue by davidozog** [Sandia-OpenSHMEM/SOS#449]
Remove the volatile qualifiers from the ivar arguments to shmem_wait routines and the lock arguments in the lock API. Rationale: Volatile qualifiers were added to several API routines in version 1.3 of the OpenSHMEM specification; however, they were later found to be unnecessary.

**Comment by jdinan** [comment]
Volatile was introduced in 09e726f6e.

**Comment by jdinan** [comment]
Closed by #514
