### ISSUE TITLE
OpenSHMEM 1.4 - change log #7 - SMA_* to SHMEM_* env vars

### ISSUE THREAD

**Issue by davidozog** [Sandia-OpenSHMEM/SOS#450]
Deprecate the SMA_* environment variables and add equivalent SHMEM_* environment variables.

**Comment by jdinan** [comment]
Check that SHMEM_ is taking precedence

**Comment by jdinan** [comment]
Verified in ```shmem_env.c``` that ```SHMEM_``` prefix is given precedence over ```SMA_```.
