### ISSUE TITLE
OpenSHMEM 1.4 - change log #9 - ordering semantics

### ISSUE THREAD

**Issue by davidozog** [Sandia-OpenSHMEM/SOS#452]
Assure the ordering semantics of memory ordering, point-to-point synchronization and collective synchronization.

**Comment by jdinan** [comment]
Check for appropriate memory barriers in quiet, fence, wait, barrier, sync, etc APIs.

**Comment by jdinan** [comment]
Possible to have an optimized build when threading and shmem_ptr (i.e. XPMEM) APIs are disabled.

**Comment by jdinan** [comment]
In ```shmem_atomic.h```, add new routine ```shmem_internal_membar``` that calls ```__sync_synchronize```.  Sprikle calls in all SHMEM synchronization routines.

**Comment by jdinan** [comment]
Related issue: #506
