### ISSUE TITLE
OpenSHMEM 1.4 - change log #16 - shmem_info_get_name

### ISSUE THREAD

**Issue by davidozog** [Sandia-OpenSHMEM/SOS#459]
Update `shmem_info_get_name`.

**Comment by jdinan** [comment]
Need a unit test to ensure this is identical to ```SHMEM_VENDOR_STRING```.

**Comment by jdinan** [comment]
[osh-1.4-rc3.pdf](https://github.com/Sandia-OpenSHMEM/SOS/files/1407569/osh-1.4-rc3.pdf)

**Comment by wrrobin** [comment]
@jdinan, I checked the spec and the repo, shmem_get_info_name() seems to be in sync with the spec. There is also a unit test already in test/unit/shmem_info.c that checks both shmem_get_info_name() and SHMEM_MAX_NAME_LEN. We just need to add a check for SHMEM_VENDOR_STRING. Should we add it in this existing test or should we add one additional unit test?

**Comment by jdinan** [comment]
@wrrobin Thanks!  Adding that to the existing test sounds good to me.

**Comment by wrrobin** [comment]
@jdinan Thanks. Should we add this change in the v1.4.0-dev?

**Comment by jdinan** [comment]
I think so.  It's not required by 1.3, so it might disrupt others who use our test suite.

**Comment by wrrobin** [comment]
Ok.

**Comment by jdinan** [comment]
Closed by #510
