### ISSUE TITLE
OpenSHMEM 1.4 - change log #18 - shmem_atomic_* renaming

### ISSUE THREAD

**Issue by davidozog** [Sandia-OpenSHMEM/SOS#462]
Add new bindings for the AMO operations with ```shmem_atomic_*``` prefix and deprecated old AMO routines.  Also update generic selection and C++ interfaces to pass through to the new interfaces.

**Comment by davidozog** [comment]
Might this be closed by #467?

**Comment by jdinan** [comment]
Nope, still have to add bindings new bindings for all of the existing AMOs and mark the old bindings as deprecated.

**Comment by davidozog** [comment]
Turns out this one might be easy with some Vim recording.  Any feedback on this so far?
[wip/new_amo_routines compared with master](https://github.com/Sandia-OpenSHMEM/SOS/compare/master...davidozog:wip/new_amo_routines?expand=1)

**Comment by davidozog** [comment]
I also get a lot of deprecation warnings in the unit tests now.  Should we update those to use the new atomics?
