### ISSUE TITLE
OpenSHMEM 1.4 - change log #20 - deprecate Fortran

### ISSUE THREAD

**Issue by davidozog** [Sandia-OpenSHMEM/SOS#464]
Deprecate the entire Fortran API.

**Comment by jdinan** [comment]
No change expected in the implementation of the Fortran bindings.

AR here is to determine whether we can emit a deprecation warning if users use the Fortran API.

**Comment by jdinan** [comment]
Option #2: Print a warning at configure time that Fortran support is deprecated.
