### ISSUE TITLE
"big_reduction" and "to_all" unit tests fail

### ISSUE THREAD

**Issue by davidozog** [Sandia-OpenSHMEM/SOS#472]
The `big_reduction` and `to_all` unit tests fail with a seg. fault in Travis and locally (on OSX):
```===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   PID 52592 RUNNING AT dmozog-mac02.hd.intel.com
=   EXIT CODE: 11
=   CLEANING UP REMAINING PROCESSES
=   YOU CAN IGNORE THE BELOW CLEANUP MESSAGES
===================================================================================
YOUR APPLICATION TERMINATED WITH THE EXIT STRING: Segmentation fault: 11 (signal 11)
This typically refers to a problem with your application.
Please see the FAQ page for debugging suggestions
```

The problem appears to be related to the latest libfabric code.  I've checked out libfabric tags `v1.5.0rc1`, `v1.5.0rc2`, `v1.5.0rc3`, and `v1.5.0`, and they all seem to *not* have issue.  This suggests that it's from a very recent commit (after August 9th) on the master branch.

**Comment by jdinan** [comment]
@shefty Are you guys tracking anything on the libfabric side that might have caused this?

**Comment by shefty** [comment]
I'm not aware of any issue.  What provider is seeing this failure?

**Comment by davidozog** [comment]
That would be the socket provider.

**Comment by jdinan** [comment]
Happens with ```SHMEM_REDUCE_ALGORITHM = linear or tree```.  No problem with ```recdbl``` (which uses software reduction instead of one-sided atomics).

**Comment by jdinan** [comment]
Another breadcrumb -- ```SHMEM_BOUNCE_SIZE=0``` makes this bug go away.  Appears related to bounce buffering (CQ).

**Comment by shefty** [comment]
I think this upstream commit to libfabric is causing the issue:

https://github.com/ofiwg/libfabric/commit/dcab6f246d8df5260d3fbf6e5d61324581cfb9d6#diff-35fe299e07cc04f3cae5c13eed96d424

The user's context is being discarded in favor of null.

**Comment by shefty** [comment]
A proposed fix is available from:  https://github.com/ofiwg/libfabric/pull/3387
This patch needs more testing.
