### ISSUE TITLE
AMO unit test coverage is incomplete in SOS v1.4

### ISSUE THREAD

**Issue by davidozog** [Sandia-OpenSHMEM/SOS#477]
After adding the new `shmem*_atomic_*` routines to SOS in PR #470, we also added new C11 tests that correspond to each of the original AMO unit tests (PR #476):
- `c11_test_shmem_add.c` -> `c11_test_shmem_atomic_add.c`
- `c11_test_shmem_fetch.c` -> `c11_test_shmem_atomic_fetch.c`
- `c11_test_shmem_inc.c` -> `c11_test_shmem_atomic_inc.c`
- `c11_test_shmem_set.c` -> `c11_test_shmem_atomic_set.c`

But this is only limited coverage over the complete set of AMO routines and types.  At some point we might want to expand the unit test coverage.

**Comment by jdinan** [comment]
Closed by #513
