### ISSUE TITLE
Add configury option to enable deprecated tests

### ISSUE THREAD

**Issue by jdinan** [Sandia-OpenSHMEM/SOS#542]
Some of the unit tests support testing of deprecated API when ```ENABLE_DEPRECATED_TESTS``` is defined.  Should we add a configury hook for this?  Or not, and test them in Travis by adding ```CFLAGS="-DENABLE_DEPRECATED_TESTS"```?

**Comment by kholland-intel** [comment]
We added a configury hook, `--enable-deprecated-tests`, which defines the `ENABLE_DEPRECATED_TESTS` flag and runs the deprecated APIs within the test suite. This feature was merged with PR #1074
