### ISSUE TITLE
OFI: Disable atomics when USE_CTX_LOCK

### ISSUE THREAD

**Issue by jdinan** [Sandia-OpenSHMEM/SOS#546]
Atomics are not needed when USE_CTX_LOCK is enabled. Wrap these atomics in macros (e.g. 
CNTR_INC/DEC/READ) to allow disabling atomics when using per-context locks.

**Comment by jdinan** [comment]
Question: if the underlying counter type is ```atomic_uint_fast64_t```, does the C standard allow you to perform simple, non-atomic arithmetic operations on it?

**Comment by davidozog** [comment]
My guess it no...?  It seems one can relax the memory ordering (`memory_order_relaxed`) which might help to reduce overhead, but you're still guaranteed atomicity in the op.

**Comment by jdinan** [comment]
Yeah, I was hoping for this to be a simple exchange of operations (non-atomic in place of atomic), but I think I should probably also swap out the ```pending_put/get_cntr``` types to be non-atomic.

**Comment by davidozog** [comment]
As to whether you can treat `atomic_uint_fast64_t` as a `uint64_t` if you so desire, it seems to work fine single-threaded, but I can't find any documentation on the matter...  It's a good question.
