### ISSUE TITLE
Evenly divide STXs into the PEs on each node

### ISSUE THREAD

**Issue by davidozog** [Sandia-OpenSHMEM/SOS#552]
We should change the `SHMEM_OFI_STX_MAX` environment variable to `SHMEM_OFI_STX_PER_NODE`; ideally detecting the number of PEs/node, and evenly dividing STXs into PEs.

**Comment by davidozog** [comment]
See PR #653

**Comment by jdinan** [comment]
@davidozog Would it be reasonable to pull this feature into 1.4.2?

**Comment by davidozog** [comment]
@jdinan Yes, I think so.

**Comment by davidozog** [comment]
Note: #653 moved to #828

**Comment by jdinan** [comment]
Closerd by #828
