### ISSUE TITLE
Dump backtrace on failure

### ISSUE THREAD

**Issue by jdinan** [Sandia-OpenSHMEM/SOS#557]
See: https://www.gnu.org/software/libc/manual/html_node/Backtraces.html

Also, may require -rdynamic in CFLAGS: https://stackoverflow.com/questions/36692315/what-exactly-does-rdynamic-do-and-when-exactly-is-it-needed

**Comment by jdinan** [comment]
Might be able to look at how GASNet does this (I think they print nice backtraces).

**Comment by wrrobin** [comment]
Closed by #795
