### ISSUE TITLE
unit test failures when mixing CentOS and Debian hosts

### ISSUE THREAD

**Issue by bsmith94** [Sandia-OpenSHMEM/SOS#565]
I see a lot of unit test failures when executing them with a mix of CentOS and Debian hosts. The tests work fine when executed only on Debian or only on CentOS.

libfabric is 1.5.0 and I have seen similar behavior when using the sockets or psm2 provider.

Overall, 63 tests in SOS/test/unit fail when executed with two hosts, one running Debian 8.7 and the other CentOS 7.4. These failures manifest as test assertion failures (e.g. incorrect value), SIGSEGVs and hangs. 

I can go into much greater detail, but would first like to know if this use case is supported.

**Comment by jdinan** [comment]
Are you running the same binary in both the Debian and CentOS hosts?  For the symmetric data segment to work, OpenSHMEM requires that all PEs be running the same binary.

**Comment by bsmith94** [comment]
That's the ticket. Thank you!

**Comment by jdinan** [comment]
The symmetric data segment unfortunately comes with some strong requirements.  But, if you stick to the symmetric heap (e.g. the ```shmalloc``` test should pass) then SOS should still work in this setup.
