### ISSUE TITLE
LibEV used in CI testing should be fetched from originator website

### ISSUE THREAD

**Issue by regrant** [Sandia-OpenSHMEM/SOS#58]
libev.schmorp.de is currently down, so Travis CI uses a copy of libev on a googledocs page. Once the main libev website is up we should migrate to using the latest version of libev directly from the official source.

**Comment by jdinan** [comment]
Still down as of 12/9/2015.

**Comment by regrant** [comment]
Looks like this is now up as of 12/11/2015. We should give it a few days to make sure things are stable and then move over to the official souce.

**Comment by jdinan** [comment]
Fixed.
