### ISSUE TITLE
Missing header for use of "PRIXPTR" in transport_xpmem.h

### ISSUE THREAD

**Issue by nspark** [Sandia-OpenSHMEM/SOS#581]
When error-checking and XPMEM are enabled, the SOS build fails because the symbol `PRIXPTR` is used in `src/transport_xpmem.h`, but `inttypes.h` is not included. This was observed with the 1.3.4 release, but [appears current](https://github.com/Sandia-OpenSHMEM/SOS/blob/6aa4a5f/src/transport_xpmem.h).

**Comment by jdinan** [comment]
Well, that didn't last long 😜  -- added v1.3.x branch for continued support of users on the v1.3.x series.  Thanks for the bug report!

**Comment by nspark** [comment]
_I_ don't mind if this only gets fixed in the 1.4.x series.

**Comment by jdinan** [comment]
Closed by #588 and #589
