### ISSUE TITLE
Provide pkg-config file for Sandia OpenSHMEM

### ISSUE THREAD

**Issue by nspark** [Sandia-OpenSHMEM/SOS#585]
### Feature Request

Provide `pkg-config` file(s) for Sandia OpenSHMEM.

**Comment by jdinan** [comment]
@nspark Any preference on the package name (e.g., `sos` or `libsma` or ...)?

**Comment by nspark** [comment]
I'd probably vote for `sandia-shmem.pc` or `sos.pc`. While systems with multiple OpenSHMEM implementations will likely use environment modules to update `PKG_CONFIG_PATH`, I don't think OpenSHMEM should try to standardize a `pkg-config` module name. AFAICT, Cray SHMEM uses `sma.pc` and OSHMEM uses `oshmem.pc`. Since there will be some variation in names between implementations, I'm inclined to think each implementation should have its own name.
