### ISSUE TITLE
SHMEM_MINOR_VERSION not reflecting 1.4 compatibility

### ISSUE THREAD

**Issue by agrippa** [Sandia-OpenSHMEM/SOS#600]
Should SHMEM_MINOR_VERSION be set to 4, now that (from my understanding) SoS is compliant with spec 1.4?

**Comment by agrippa** [comment]
In https://github.com/Sandia-OpenSHMEM/SOS/blob/master/mpp/shmem.h4.in

**Comment by davidozog** [comment]
Good catch!  Are we also 1.4-compliant with the (deprecated) Fortran interface as well?
  :wink:  `SHMEM_MINOR_VERSION` is also [defined there](https://github.com/Sandia-OpenSHMEM/SOS/blob/master/mpp/shmem.fh.in#L50).

**Comment by jdinan** [comment]
Thanks for the bug report!  All yours, @davidozog

**Comment by davidozog** [comment]
Closed by #601
