### ISSUE TITLE
Lazy connections with PSM2 and libfabric >v1.6?

### ISSUE THREAD

**Issue by davidozog** [Sandia-OpenSHMEM/SOS#667]
From GASNet [58d396d](https://bitbucket.org/berkeleylab/gasnet/commits/58d396dfcffbd46562cfb555bd633cb1c8229043):

"In libfabric v1.6, the psm2 provider transitioned to using separate psm2 endpoints for each ofi endpoint, whereas in the past all communication was multiplexed over a single psm2 endpoint. Setting this variable ensures that unnecessary connections between remote endpoints which never communicate are not made, which can cause slow tear-down. This variable is set before calling fi_getinfo() as the provider may read its environment variables in that function call."

Should we enable `FI_PSM2_LAZY_CONN` in SOS by default?

**Comment by jdinan** [comment]
I think this will require testing at scale to see how it impacts us.  Given the importance of global communication, this may not be a good default.

**Comment by davidozog** [comment]
Yup!  I was just about to look into that, initially with a simple hello test.  If I understand correctly, this only affects "tear-down" so shmem_finalize?

**Comment by jdinan** [comment]
Good to know!  The concern I had is that it could also cause extra overhead in applications where each PE communicates with all other PEs (e.g. ISx, GUPS, or PRK transpose).

**Comment by sayantansur** [comment]
@j-xiong.

What I heard from Jianxin is that it sometimes depends on pattern of communication. Jianxin, could you advise the SOS folks?

**Comment by j-xiong** [comment]
Lazy connection moves the connection setup overhead from initialization time to the very first communication between each endpoint pair. Usually the overhead can be amortized over later communication activities. For applications that have few communications over each connection, the overhead can be more perceivable. But even for such cases, the overall time may be similar because the initialization time is reduced.

**Comment by davidozog** [comment]
Great, thanks!  (Also note epaulson10's comment related to this issue [here](https://github.com/Sandia-OpenSHMEM/SOS/issues/646#issuecomment-380294288)).

I haven't yet noticed any consistent overhead in our key applications (gups, ISx, shmem_perf_suite), even looking at shmem_init and finalize in isolation.  It seems to me that execution variability (noise) might make perceiving these effects a bit challenging...

Anyway, I'd say it's alright to defer setting `FI_PSM2_LAZY_CONN` to our power users.  I've documented it on the PSM2 Performance Tuning section on the [wiki](https://github.com/Sandia-OpenSHMEM/SOS/wiki/Performance-Tuning#psm2-provider).  Does that sound good, @jdinan?

**Comment by jdinan** [comment]
Sounds good to me.  With that update to the wiki, it seems like we can close this issue.
