### ISSUE TITLE
1.4.1 Release Update

### ISSUE THREAD

**Issue by jdinan** [Sandia-OpenSHMEM/SOS#672]
- [x] Update version number to v1.4.1
- [x] Update NEWS
- [x] Double check release checklist: https://github.com/Sandia-OpenSHMEM/SOS/wiki/Release-Checklist

**Comment by wrrobin** [comment]
Most recent numbers for PSM2 are available here: http://fmneptjenkins.amr.corp.intel.com:8080/job/report_perf_suite/Report/

**Comment by davidozog** [comment]
See PR #676
