### ISSUE TITLE
Describe setting `HFI_UNIT` somewhere on wiki

### ISSUE THREAD

**Issue by davidozog** [Sandia-OpenSHMEM/SOS#674]
See issue #665 - setting `HFI_UNIT` can restrict communication to a particular HFI.

**Comment by wrrobin** [comment]
Sure. I can take it. It is 0 indexed. Not sure whether it is relevant only for PSM2 though.

**Comment by wrrobin** [comment]
I have checked in one version here: https://github.com/Sandia-OpenSHMEM/SOS/wiki/Performance-Tuning. Please check and suggest if any change is needed.

**Comment by davidozog** [comment]
Great, thanks!
