### ISSUE TITLE
Manual progress should enable thread completion

### ISSUE THREAD

**Issue by davidozog** [Sandia-OpenSHMEM/SOS#715]
When passing `--enable-manual-progress` to configure, we should be sure that ~~`USE_THREAD_COMPLETION`~~ `USE_COMPLETION_POLLING` is defined, otherwise `shmem_transport_probe()` is not called during `shmem_transport_put_quiet` and `shmem_transport_get_wait`.  I've seen this unexpectedly cause progress stalling with the libfabric PSM2 provider, despite having set manual progress.

**Comment by jdinan** [comment]
Resolved?

**Comment by davidozog** [comment]
Yes, by #729
