### ISSUE TITLE
Enable MR_SCALABLE with MR_RMA_EVENT (docs update)

### ISSUE THREAD

**Issue by jdinan** [Sandia-OpenSHMEM/SOS#719]
Update configury to automatically enable MR_SCALABLE when MR_RMA_EVENT is enabled.  In fact, it would be good to move to a parameter like `--with-ofi-mr=[basic,scalable,rma-event]` to prevent users from giving nonsensical combinations of these arguments.

Ref: #713

**Comment by jdinan** [comment]
Should be fixed.  Make sure to mention in NEWS.

**Comment by jdinan** [comment]
And update the wiki

**Comment by davidozog** [comment]
Note: Cray XC wiki says to use `--disable-mr-scalable`.  (Also, `--enable-threads`)

**Comment by jdinan** [comment]
This would become `--enable-ofi-mr=basic`.
