### ISSUE TITLE
Update PMIx testing to use PRRTE

### ISSUE THREAD

**Issue by jdinan** [Sandia-OpenSHMEM/SOS#742]
Update PMIx testing to use [PRRTE](https://github.com/pmix/prrte) for process management instead of OpenMPI.

**Comment by wrrobin** [comment]
@jdinan We can move this 1.4.x. I have tested with `sync` but the tests are still failing due to resource limitation.

**Comment by jdinan** [comment]
🔥 🚒 🙌
