### ISSUE TITLE
Portals 4 Release Testing

### ISSUE THREAD

**Issue by jdinan** [Sandia-OpenSHMEM/SOS#758]
Run the Portals 4 tests on IB cluster.

@wrrobin Is this automated now?

**Comment by wrrobin** [comment]
Please assign me. I am going to add it right now.

**Comment by wrrobin** [comment]
Added tests in Jenkins and tests are passing

**Comment by wrrobin** [comment]
@jdinan I have launched 9 tests for portals4 with different configurations. 3 of them passed all the tests. However, the rest 6 (none and memcpy for local transport) gets stuck at the `shmemlatency` test (passing other unit tests) and eventually times out. Any thoughts?

**Comment by jdinan** [comment]
I'm able to reproduce this in manual testing.  I have not been enabling lengthy tests in the Portals 4 release testing.  The `shmemlatency` test in particular is kind of gross.  It only works on little endian systems because of how it casts between `char` and `long` on the data buffer.

**Comment by jdinan** [comment]
This test also fails on v1.3.5

**Comment by wrrobin** [comment]
Disabling lengthy tests let other tests to run and all the tests pass for different local transports and with/without threads. Is there any other configure flags that we should test for portals?

**Comment by jdinan** [comment]
Thanks.  I have not run lengthy tests with Portals in the past.  I do usually run make check with varying numbers of PEs, which I did earlier today on Neptune.  I think we can safely file the `shmemlatency` issue for future exploration, since it's not being introduced here and is coming from a questionable unit test.
