### ISSUE TITLE
GNI Release Testing

### ISSUE THREAD

**Issue by jdinan** [Sandia-OpenSHMEM/SOS#759]

**Comment by davidozog** [comment]
As commented in #639, some tests always seg fault with libfabric v1.6.x using more than 1 thread.

Unfortunately, Cori is in maintenance this week and some of next week, so this could be held up a bit.  Last I tried on Edison, I ran into software dependence versioning issues, but I'll try again.

**Comment by davidozog** [comment]
Cori's back, and all unit test (except `global_exit`) pass with libfabric v1.6.1 and the following SOS configure options:
```
--enable-ofi-mr=basic --with-xpmem=/opt/cray/xpmem/default --enable-completion-polling --with-pmi=/opt/cray/pe/pmi/default --enable-hard-polling
```
using ` make check TEST_RUNNER="srun -N 2 -n 4"`

I'll test what other Travis rows I can, but it's a little tough to get jobs through, so any particular suggestions?

**Comment by davidozog** [comment]
More good news: the #639 bug does not appear to exist with libfabric v1.6.1 or v1.6.x.  I may have confused the v1.6.x seg fault with #763, which was recently fixed.  But I still see the fault about half the time using libfabric v1.6.0.

**Comment by davidozog** [comment]
Another side note:  I had no trouble building and testing SOS + libfabric v1.6.1 on Edison at NERSC.  All unit tests pass there as well.

**Comment by jdinan** [comment]
Great!  Anything on the [wiki](https://github.com/Sandia-OpenSHMEM/SOS/wiki/OFI-Build-Instructions-Cray-XC) that should be updated?  Looks like the wiki says to use Mr. Basic?

**Comment by davidozog** [comment]
Yup, Mr. Basic.  Also note the PMI path moved from `/opt/cray/pmi/default` to `/opt/cray/pe/pmi/default` on Cori and Edison.

**Comment by davidozog** [comment]
@jdinan I've just updated the [Cray XC wiki page](https://github.com/Sandia-OpenSHMEM/SOS/wiki/Cray-XC-Build-Instructions).  Please feel free to review it and close [this](#759) issue and #719 if you're happy with it.

**Comment by jdinan** [comment]
Thanks!
