### ISSUE TITLE
Mellanox tests failing in Travis

### ISSUE THREAD

**Issue by davidozog** [Sandia-OpenSHMEM/SOS#791]
In Travis, the following test fails on all rows:

oshrun -np 4 $PWD/install/bin/oshmem_test exec --task=basic:static

It's related to the most recent commit here:
https://github.com/openshmem-org/tests-mellanox/commit/50a19a296994e37d2352db0643fd056c0739e5a8

**Comment by davidozog** [comment]
I've proposed a fix here:
https://github.com/openshmem-org/tests-mellanox/pull/38

@jdinan / @wrrobin, does that PR look right?

**Comment by wrrobin** [comment]
It looks right to me. I am validating whether Jenkins also reports the same error.

**Comment by jdinan** [comment]
@davidozog Fix was merged into tests-mellanox.  Could you try re-enabling the affected test?

**Comment by jdinan** [comment]
Closed by #821
