### ISSUE TITLE
Contexts tests require context creation to succeed

### ISSUE THREAD

**Issue by jdinan** [Sandia-OpenSHMEM/SOS#798]
All of the SOS tests that use contexts assume that context creation should succeed.  However, this is not required by the spec.  Should we exit with success in these cases or use the default context or something else?

**Comment by jdinan** [comment]
This is mostly resolved.  The only remaining cases are in the perf suite.

**Comment by jdinan** [comment]
@minsii Anything else we missed?

**Comment by minsii** [comment]
@jdinan Thanks for the change ! We will test it today and let you know

**Comment by minsii** [comment]
@jdinan The `test/unit` and `test/apps` give us all green now :-) Thanks for the fix. I just noticed that `test/performance` still shows error of failed context creation.

**Comment by jdinan** [comment]
The performance tests that use contexts are a bit more tricky.  If the implementation can't create contexts, then it's better for the benchmark to exit than to produce meaningless results.

**Comment by minsii** [comment]
I see. Is it possible to make them return without error ?

**Comment by wrrobin** [comment]
Like the other fixes, if we make these tests to use the default context, then the results will be undefined since we have already initialized with THREAD_MULTIPLE. @jdinan Would it be allowed to set the thread level to SERIALIZED if the context creation fails?

**Comment by jdinan** [comment]
I think it's better to exit the test.  Perhaps we can exit with success instead of error?

**Comment by wrrobin** [comment]
Yes, that is of-course do-able, but makes little sense for success as these are perf tests with contexts and the context creation failed.

**Comment by jdinan** [comment]
We would print an error message and exit with code 0.  This is the same thing we do with tests that require a specific number of PEs, so that they don't disrupt automated testing.

**Comment by wrrobin** [comment]
Ok. Will do.

**Comment by minsii** [comment]
Thanks @jdinan and @wrrobin !

**Comment by jdinan** [comment]
Closed by #849
