### ISSUE TITLE
All PEs have rank 0 of 1 w/ some launchers

### ISSUE THREAD

**Issue by davidozog** [Sandia-OpenSHMEM/SOS#803]
Some launchers (most notably, launchers from certain versions/builds of OpenMPI) technically pass all SOS unit tests, but they are not actually communicating.  When this happens, the "Hello World" test output looks something like this (for 3 PEs):
```
Hello World from 0 of 1
Hello World from 0 of 1
Hello World from 0 of 1
```
The severity of this is somewhat low, because a simple workaround is to use a Hydra launcher.  But I'm thinking it might be possible to write a test that detects this situation easily/portably with some unix IPC, which might be useful.

**Comment by jdinan** [comment]
Duplicate of #788
