### ISSUE TITLE
Separate types and constants from shmem.h for use in pshmem.h

### ISSUE THREAD

**Issue by wrrobin** [Sandia-OpenSHMEM/SOS#808]

**Comment by jdinan** [comment]
I actually wrote this up locally and was noodling with it.  The change somehow broke one of the shmemx tests.  Still trying to figure out what happened.  I can push the branch if you want to tinker with it.

**Comment by wrrobin** [comment]
Yes, I was doing the same. :) The issue was with the shmemx data types (shmemx_ct_t and shmemx_pcntr_t) missing for me. The thing is pshmem.h includes both shmem and shmemx.h and shmemx.h includes shmem.h itself. So, I tried removing both from pshmem and adding the data types from a separate file. Sure, please push the branch and I will work on that.
