### ISSUE TITLE
Cannot get SOS to use the verbs provider

### ISSUE THREAD

**Issue by lyu** [Sandia-OpenSHMEM/SOS#851]
Hello. I am trying to install SOS over libfabric on our Mellanox ConnectX-5 cluster, but it keeps saying the verbs providers are invalid. It works fine if I enable sockets support in libfabric, but of course the internode bandwidth will be bad.

System: ```CentOS 7.5.1804```
Kernel: ```Linux 3.10.0-862.2.3.el7```

libfabric: ```1.7.0```
libfabric config: ```--prefix=$INSTALLPATH --disable-sockets --disable-tcp --disable-udp --disable-mlx``` (I had to disable the mlx provider, otherwise the build tries to find an old API in UCX and crashes)

Hydra: ```3.3```
Hydra config: ```--prefix=$INSTALLPATH --enable-g=none --without-x --with-pbs=$PBS_DIR```

SOS: ```1.4.3```
SOS config: ```--prefix=$INSTALLPATH --enable-completion-polling --enable-remote-virtual-addressing --enable-pmi-simple --disable-fortran --with-cma --with-ofi=$INSTALLPATH```

Output of ```fi_info -c "FI_RMA|FI_ATOMIC" -t FI_EP_RDM```:

```
provider: verbs;ofi_rxm
    fabric: IB-0xfe80000000000000
    domain: mlx5_0
    version: 1.0
    type: FI_EP_RDM
    protocol: FI_PROTO_RXM
provider: verbs;ofi_rxd
    fabric: IB-0xfe80000000000000
    domain: mlx5_0-dgram
    version: 1.0
    type: FI_EP_RDM
    protocol: FI_PROTO_RXD
provider: shm
    fabric: shm
    domain: shm
    version: 1.0
    type: FI_EP_RDM
    protocol: FI_PROTO_SHM
```

If I try ```fi_pingpong -p verbs -e rdm -S all``` between two nodes, I do get decent numbers for all the sizes (0 ~ 6m). So I guess I should open an issues here rather than in the libfabric repo.

But no matter how I set ```SHMEM_OFI_PROVIDER```, ```SHMEM_OFI_FABRIC```, ```SHMEM_OFI_DOMAIN``` according to the output of ```fi_info```, or leave it to ```<auto>```, all I can get is ```OFI transport did not find any valid fabric services (provider=xxx)```. I have tried to set ```SHMEM_OFI_PROVIDER``` to ```verbs```, ```verbs;ofi_rxm```, ```verbs;ofi_rxd```, ```ofi_rxm```, ```ofi_rxd```, all do not work.

I have had this problem since forever and it is not specific to any specific version of libfabric or SOS. Could you please help me figure out what's wrong with my setup? Thank you!

**Comment by jdinan** [comment]
Thanks for the issue report.  SOS isn't working yet with the RXM provider, but it's on our to-do list.  I'm looking into this to see what's needed (potentially on both SOS/RXM sides).  I'll post my findings here within the next few days.

**Comment by jdinan** [comment]
We've been working with the RXM provider author and other libfabric folks and have resolved a number of issues with getting SOS up and running with the RXM provider.  Unfortunately, RXM doesn't yet support automatic progress with fabric atomics, which is a requirement for OpenSHMEM.  The libfabric folks are looking into this, but it could be several weeks or more before it's supported.  We do plan for SOS to support the RXM provider, but unfortunately we're not quite there yet.

**Comment by lyu** [comment]
Thank you for the answer! Closing this issue.

**Comment by jdinan** [comment]
@lyu Wanted to let you know that we're making progress on this.  With the libfabric v1.8.0rc1 release, all of the single-threaded SOS tests are passing with verbs;rxm.

**Comment by lyu** [comment]
@jdinan Thank you! I will give it a try later.

**Comment by marcinz** [comment]
I am not able to get it to work with SOS master (as of now). I get from `fi_info`:

```provider: verbs
    fabric: IB-0xfe80000000000000
    domain: mlx4_0
    version: 1.0
    type: FI_EP_MSG
    protocol: FI_PROTO_RDMA_CM_IB_RC
provider: verbs
    fabric: IB-0xfe80000000000000
    domain: mlx4_0-xrc
    version: 1.0
    type: FI_EP_MSG
    protocol: FI_PROTO_RDMA_CM_IB_XRC
provider: verbs
    fabric: IB-0xfe80000000000000
    domain: mlx4_0-dgram
    version: 1.0
    type: FI_EP_DGRAM
    protocol: FI_PROTO_IB_UD
provider: verbs;ofi_rxm
    fabric: IB-0xfe80000000000000
    domain: mlx4_0
    version: 1.0
    type: FI_EP_RDM
    protocol: FI_PROTO_RXM```

Then I configure with `CC=mpicc CXX=mpicxx ./configure --prefix=/lustre/zale916/software/SOS-master-install --enable-pmi-mpi --with-cma --with-ofi=/share/apps/libfabric/1.8.0/`. Then I tried `make -j 20 check TEST_RUNNER="srun -n 2 -N 2" SHMEM_OFI_PROVIDER="sockets"`, which works fine. However, `make -j 20 check TEST_RUNNER="srun -n 2 -N 2" SHMEM_OFI_PROVIDER="verbs;rxm"` fails with:

```[0000] WARN:  transport_ofi.c:1146: query_for_fabric
[0000]        OFI transport did not find any valid fabric services (provider=verbs;ofi_rxm)
[0000] ERROR: init.c:370: shmem_internal_init
[0000]        Transport init failed (-61)```

I tried variations such as `verbs;rxm`, `verbs`, `verbs;*`, and `verbs*`. 

Am I doing something wrong entirely, or is something not working properly?

**Comment by davidozog** [comment]
@marcinz Your build looks good at a glance - I think you should be setting `SHMEM_OFI_PROVIDER="verbs;ofi_rxm"`, but it looks like that's the provider being attempted.

We might get a better hint if you set `FI_LOG_LEVEL=debug`.  Does that print a more specific error for why the provider is invalid?  (I have a feeling it might be fixed with `--enable-ofi-mr=basic`, but that's just a guess).

**Comment by marcinz** [comment]
Thank you! `--enable-ofi-mr=basic` works. I would have never thought about this myself. Is this something that is documented somewhere? I am just curious why this changes everything.

I am seeing two testes hang now:

```
FAIL: mt_a2a
FAIL: mt_lock_test
```

It could be because of the way that I run my test, or maybe there is some issue. However, I think whatever works may be just enough for what I am trying to do.

**Comment by davidozog** [comment]
SOS's support for the rxm provider is very experimental, so there is no full-fledged documentation on it at the moment.  The basic memory registration (mr) change is also not well-documented... my apologies.  Once the dust settles, we'll probably make a wiki page documenting verbs/rxm setup.

I've heard those two multi-threaded (mt) tests (mt_a2a/lock_test) pass with some recent developments in the libfabric rxm provider (@jdinan and/or @a-ilango may know more).  I'm not sure it's pushed yet, but you might consider keeping up-to-date with libfabric master if you plan on having multiple threads make OpenSHMEM calls.

**Comment by jdinan** [comment]
@marcinz Support for RXM is brand new and not yet documented (should be after our upcoming release).  Make sure to use the latest version of libfabric.  You will need to configure with `--enable-hard-polling` and `--enable-ofi-mr=basic` flags.  Enabling manual progress `--enable-manual-progress` at configure time may also improve performance.  If you plan to run anything multithreaded, also set `FI_MR_CACHE_MAX_COUNT=0` environment variable to work around an issue in the libfabric memory registration cache.  Configuring with `--enable-thread-completion` may also improve performance for multithreaded applications.  We have not yet studied which configuration options give the best performance.

**Comment by jdinan** [comment]
@lyu See above, we have experimental support for RXM/Verbs available now in SOS.

**Comment by jain-jainendra** [comment]
Hi, I am also facing the same error. It is not getting resolved by building using --enable-ofi-mr=basic. Any suggestion will help.
$ oshrun -n 2 ./a.out
[0000] WARN:  transport_ofi.c:1420: query_for_fabric
[0000]        OFI transport did not find any valid fabric services (provider==cxi)
[0000] ERROR: init.c:466: shmem_internal_heap_postinit
[0000]        Transport init failed (-61)

**Comment by wrrobin** [comment]
@jain-jainendra - Thanks for reaching out. Could you please share a little more on the config flags you are trying? Is it the CXI provider or the verbs provider that you would like to enable with SOS?
Also, please open a new GitHub issue if the error persists.
