### ISSUE TITLE
seg fault in shmem_global_exit()

### ISSUE THREAD

**Issue by davidozog** [Sandia-OpenSHMEM/SOS#866]
I'm getting a seg fault on Mac OSX with clang when calling `shmem_global_exit()`.
My call stack:

```
shmem_util_backtrace at backtrace.c:184:21
shmem_runtime_abort(exit_code=1, msg="PE 0 called shmem_global_exit with status 1") at runtime-pmi.c:139:5
shmem_internal_global_exit(status=1) at init.c:502:5
shmem_global_exit(status=1) at init_c.c:98:5
main(argc=1, argv=0x00007ffeefbff310) at shmemx_team_translate.c:25:9
```
I think my debugger is saying that 
`
char *method = shmem_internal_params.BACKTRACE;
`
results in `method` as a `NULL` pointer (though I would expect it should be an empty string), so `strcmp` seg faults.

**Comment by davidozog** [comment]
Also seeing this in Ubuntu 16.04 with gcc.

**Comment by wrrobin** [comment]
@davidozog Thanks for catching this and sorry that I missed your issue submission earlier.

**Comment by davidozog** [comment]
@wrrobin No problem!  It was my fault, as explained in PR #867
