### ISSUE TITLE
How to launch a job using oshrun and change the default launcher from slurm to ssh?

### ISSUE THREAD

**Issue by anshumang** [Sandia-OpenSHMEM/SOS#876]
I tried the following-
`/path/to/oshrun -n 2 -N 2 -w somehost1,somehost2 /path/to/binary`
and the get the following error output-
srun: error: Unable to allocate resources: Requested node configuration is not available

I suppose what I am looking for is the equivalent of `-launcher ssh` that Spectrum MPI provides.

Also by `-n 2 -N 2` I intend to run 2 processes, 1 per node. Is that correct?

**Comment by jdinan** [comment]
In SOS, oshrun is just a simple wrapper that calls the system launcher.  All of the arguments are passed through to the launcher that gets called.  With SOS you can set the `OSHRUN_LAUNCHER` environment variable (there is also a configure option) to set the program that is run as the launcher.  You can just call the launcher (mpiexec, srun, etc) directly.

**Comment by anshumang** [comment]
Calling mpich launcher directy works for me. Something like the following-
`/path/to/mpich/intall/bin/mpirun -n 2 -ppn 1 -hosts somehost1,somehost2 /path/to/SOS/linked/binary`
I need to have `LD_LIBRARY_PATH` pointing to `/path/to/SOS/install/lib` to resolve `libsma.so` dependency in my binary.
Thanks for the help !
