### ISSUE TITLE
Clarification in SOS 1.5 document would be helpful

### ISSUE THREAD

**Issue by lriesen** [Sandia-OpenSHMEM/SOS#936]
Reading about the team based collectives it wasn't clear to me at first how much data was being sent in "mem" functions like:

shmem_broadcastmem(shmem_team_t team, void *dest, const void *source, size_t nelems, int PE_root)

since the document says "nelems" is "the number of elements in source".  I figure "nelems" must be number of bytes, and Dave confirms this is the case.    Perhaps in the beginning of the collectives sections this can be stated.

Instead of:
![doc](https://user-images.githubusercontent.com/10623632/75299016-cce7e480-57e8-11ea-8a6a-5f67d2bf0b5c.png)
 
How about:

- shmem_team_sync
- shmem_(type)_broadcast and shmem_broadcastmem (where element is one byte)
- shmem_(type)_collect and shmem_collectmem (where element is one byte)

and so on.

**Comment by jdinan** [comment]
@lriesen Thanks for the feedback. I created an issue on the OpenSHMEM specification project and assigned to the relevant section committee (https://github.com/openshmem-org/specification/issues/376).

**Comment by davidozog** [comment]
Closed by https://github.com/openshmem-org/specification/issues/376

Thanks @lriesen
