### ISSUE TITLE
Set ctx to SHMEM_CTX_INVALID when context creation is unsuccessful

### ISSUE THREAD

**Issue by wrrobin** [Sandia-OpenSHMEM/SOS#942]
`shmem_transport_ctx_create` should assign CTX_INVALID in case of context creation failure. May need to omit the check for NULL later.

**Comment by davidozog** [comment]
This is closed, right @wrrobin?

**Comment by wrrobin** [comment]
Yes, thanks @davidozog. Closed by #941
