### ISSUE TITLE
OS X shmem_internal_init transport startup failed

### ISSUE THREAD

**Issue by wwc559** [Sandia-OpenSHMEM/SOS#947]
I am unsure if this is a SOS bug or an installation problem on my part, but when I try to run the "hello" test, I get the error message quoted below on OS X Catalina after doing a clean brew install on libfabric and a clean build of hydra-3.3.2.  Make check in hydra produces no errors. fi_info produces a reasonable looking set of sockets providers.

Happy to provide more info if needed!

Thanks!

Bill Carlson

oshrun -n 2 ./hello
[0000] WARN:  transport_ofi.c:1070: populate_av
[0000]        av insert failed
[0000] ERROR: init.c:394: shmem_internal_init
[0000]        Transport startup failed (1)
[0001] WARN:  transport_ofi.c:1070: populate_av
[0001]        av insert failed
[0001] ERROR: init.c:394: shmem_internal_init
[0001]        Transport startup failed (1)

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   PID 13814 RUNNING AT Bills-MacBook-Pro.local
=   EXIT CODE: 6
=   CLEANING UP REMAINING PROCESSES
=   YOU CAN IGNORE THE BELOW CLEANUP MESSAGES
===================================================================================
YOUR APPLICATION TERMINATED WITH THE EXIT STRING: Abort trap: 6 (signal 6)
This typically refers to a problem with your application.
Please see the FAQ page for debugging suggestions

**Comment by jdinan** [comment]
@wwc559 Could you set `SHMEM_INFO=1` and `SHMEM_DEBUG=1` environment variables and paste the output for us? You could try setting `SHMEM_OFI_PROVIDER=sockets` to ensure SOS picks the right provider. I have also had VPN-related issues on my laptop that required me to set `SHMEM_OFI_DOMAIN=lo0` to direct libfabric traffic to the loopback device.

**Comment by wwc559** [comment]
SHMEM_OFI_DOMAIN=lo0 did the trick, passes all tests now!

Thanks!

Bill
