### ISSUE TITLE
Inter-operability conformance to 1.5

### ISSUE THREAD

**Issue by wrrobin** [Sandia-OpenSHMEM/SOS#948]
Check to see whether PMI-MPI capability in SOS conforms the recent spec changes in 1.5. A relevant PMI2 issue #928

**Comment by wrrobin** [comment]
@davidozog There are two spec examples for MPI SHMEM hybrid programs, which might be better to merge into SOS and check with `--enable-pmi-mpi` flag. Thoughts?

**Comment by davidozog** [comment]
Yeah, that sounds great.

It will likely require a “guard” in autotools to enable the test when `—enable-pmi-mpi` is set, right?
