### ISSUE TITLE
Deadlock in `zero_comms` with portals transport

### ISSUE THREAD

**Issue by davidozog** [Sandia-OpenSHMEM/SOS#958]
This came up while testing the Portals transport for a v1.5.0 release: 

Unit test `zero_comms` (doing a shmem_putmem with len=0 and src=dest=NULL) appears to be stuck in `PtlEQWait` after a small change to support individually completed puts in UCX in this commit: https://github.com/Sandia-OpenSHMEM/SOS/commit/64885a10a97ba04549626a5a124757c1d9a65ae7

It appears to only be an issue when bounce buffering is enabled.  In Portals, the default context seems to be hard-coded to do bounce buffering (even when passing --disable-bounce-buffering), but I'm not sure why...  If I remove that hard-coded option, then all seems ok, so perhaps that could be a quick fix to this issue?

Otherwise, reverting the len==0 change in https://github.com/Sandia-OpenSHMEM/SOS/commit/64885a10a97ba04549626a5a124757c1d9a65ae7 will likely break zero-length puts in UCX.  Is that true @jdinan?

On that note, the spec suggests len=0 and ptr=NULL should have defined behavior, but not necessarily that any communication/completion event must occur.  Unless I'm missing something?  I don't see much clarification in the RMA section, but perhaps it's elsewhere.

Anyway, any other thoughts on this?  Would it be ok to disable bounce buffering on the default context in Portals?

**Comment by jdinan** [comment]
It looks like there is an assumption that when `shmem_transport_portals4_drain_eq` is called by `shmem_transport_put_wait` there must be an event that will show up in the queue. Hence the blocking call to `PtlEQWait`. The bug appears to be that Portals is waiting for `completion` to reach `0` while the other transports are waiting for it to be nonzero. Hence `drain_eq` is being called when it should not be.

**Comment by jdinan** [comment]
I think the `len == 0` handling in `shmem_internal_put_nb` is backwards. We should be treating `completion` as a reference count, not a boolean. So, it should be getting set to 0 instead of 1. The UCX transport code will need a minor update to support this.

**Comment by davidozog** [comment]
@jdinan - Cool, agreed.  It looks like `completion` is set to 0 a layer up (in `data_c.c4`) so we can revert `shmem_internal_put_nb` to simply return when `len == 0`, correct?

If so, can you please help with the minor UCX update?  I don't immediately see what to do there...
