### ISSUE TITLE
Bug in shmemx_team_reuse_teams.c 

### ISSUE THREAD

**Issue by akhillanger** [Sandia-OpenSHMEM/SOS#969]
Only the PEs in the parent team should call the shmem_team_split_strided API. However, in the test, all the PEs are calling it irrespective of the PEs in the parent team.

**Comment by davidozog** [comment]
Thanks @akhillanger!  I'm surprised this test has been passing...  I think we can fix this with a very small change, something like this:
```
diff --git a/test/shmemx/shmemx_team_reuse_teams.c b/test/shmemx/shmemx_team_reuse_teams.c
index 0aeb59d..c858795 100644
--- a/test/shmemx/shmemx_team_reuse_teams.c
+++ b/test/shmemx/shmemx_team_reuse_teams.c
@@ -56,6 +56,8 @@ int main(void)
                 shmemx_team_translate_pe(old_team, 1, SHMEMX_TEAM_WORLD), 1, shmemx_team_n_pes(old_team)-1);
         }
 
+        if (me < i-1) break; // or continue...
+
         ret = shmemx_team_split_strided(old_team, 1, 1, shmemx_team_n_pes(old_team)-1, NULL, 0, &new_team);
         if (old_team != SHMEMX_TEAM_INVALID && ret) ++errors;
```

If this looks good, perhaps we can include this immediately after the merge of #955, since this test is about to move out of the `shmemx` collection and into the `unit` collection.  Please let me know if you see any issues with that approach.

**Comment by jdinan** [comment]
I think the test is relying on this behavior:
> If parent_team compares equal to SHMEM_TEAM_INVALID, then no new team will be created and new_team will be assigned the value SHMEM_TEAM_INVALID.

**Comment by jdinan** [comment]
If this is the case, it's a good test and we should keep it.

**Comment by davidozog** [comment]
@jdinan - `shmem_team_split_strided` currently returns 1 when `parent_team == SHMEM_TEAM_INVALID`, which may be problematic in this test, right?  Should that be returning 0?  That's my hunch at the moment...  If memory serves, this may have been a relatively late change to the v1.5 spec:

>On successful creation of the new team:
...
• Those PEs in the parent team that are not members of the new team will have new_team assigned to SHMEM_TEAM_INVALID.
• shmem_team_split_strided will return zero to all PEs in the parent team.

To my eye, that doesn't exactly specify what value is returned for PEs that are not in the parent team (or in the new team).

**Comment by davidozog** [comment]
Actually... this test is probably fine.  I didn't realize the error check was 
`         if (old_team != SHMEMX_TEAM_INVALID && ret) ++errors;`
and not
`         if (old_team != SHMEMX_TEAM_INVALID || ret) ++errors;`

But it still seems the behavior is perhaps underspecified for PEs that are in neither the parent or the child team.

**Comment by jdinan** [comment]
I think `shmem_team_split_strided` should return nonzero since the team was not successfully created. I agree this should be specified more clearly in the spec. Would you mind filing an issue against the OpenSHMEM spec for this?

**Comment by davidozog** [comment]
I think we can safely close this - please let me know otherwise @akhillanger.
