### ISSUE TITLE
test shmem_team_collect_active_set has bad number of arguments for shmem_sync

### ISSUE THREAD

**Issue by BryantLam** [Sandia-OpenSHMEM/SOS#978]
`make check` fails on master https://github.com/Sandia-OpenSHMEM/SOS/commit/b7ce94e656bd638df1b351ba59a67a959ed55b74 in file `shmem_team_collect_active_set.c:108:13`.

`error: too few arguments to function 'shmem_sync'`

**Comment by jdinan** [comment]
I think this is fixed by #976 if you want to give it a try.

@davidozog Is #976 ready to merge?

**Comment by davidozog** [comment]
Yes, #976 is ready @jdinan.  Sorry, thought I had approved that, but I guess it never had a review request.  Please go ahead and merge, thanks.  And please let us know if that fixes the issue, @BryantLam - thanks!

**Comment by BryantLam** [comment]
I fixed it manually by changing those functions to `shmem_team_sync`. That PR does effectively the same thing. LGTM!
