### ISSUE TITLE
XPMEM in Travis not working

### ISSUE THREAD

**Issue by davidozog** [Sandia-OpenSHMEM/SOS#979]
The last 2 pull requests fail on the `--with-xpmem` rows:
https://travis-ci.org/github/Sandia-OpenSHMEM/SOS/builds/736493906
https://travis-ci.org/github/Sandia-OpenSHMEM/SOS/builds/736497434

With a problem during `insmod`:
```
insmod: ERROR: could not load module /home/travis/travis/install/xpmem/lib/modules/4.15.0-1077-gcp/xpmem.ko: No such file or directory
```

It looks to me like the XPMEM installation went fine... but the path might be wrong to the kernel module file for some reason.  There has been a lot of activity on https://github.com/hjelmn/xpmem lately... but looks unrelated at a glance.
Have you seen anything like this @jdinan or @shamisp?

**Comment by jdinan** [comment]
If the XPMEM build isn't failing, maybe this line is no longer producing the right path?
```
sudo insmod $TRAVIS_INSTALL/xpmem/lib/modules/`uname -r`/xpmem.ko
```

**Comment by jdinan** [comment]
It looks like something may have in where the kernel module gets installed:
```
/usr/bin/install -c -m 644 xpmem.ko '/home/travis/travis/install/xpmem/lib/modules/4.15.0-1077-gcp/kernel/xpmem'
...
insmod: ERROR: could not load module /home/travis/travis/install/xpmem/lib/modules/4.15.0-1077-gcp/xpmem.ko: No such file or directory
```

**Comment by davidozog** [comment]
Oh yeah, I see that in the Travis log now... so it must be a change on the Ubuntu/linux or GNU make side of things - not XPMEM itself.

Well, thanks for fixing it anyway, @jdinan!
