### ISSUE TITLE
OPAL/OMPI Configury may be out of date

### ISSUE THREAD

**Issue by davidozog** [Sandia-OpenSHMEM/SOS#985]
We should compare our OPAL/OMPI configury files with what's upstream at github.com:open-mpi/ompi.git.  At a glance, I see a lot of changes (mostly whitespace), but I think we can safely take these and test them.

It's probably best to do this after the v1.5.0 release so we can test it for a while.

**Comment by kholland-intel** [comment]
The OPAL/OMPI config files have been updated to align with the ompi stable release, v4.1.0. At the time of the posting of this issue, that was the latest stable release. There has since been another release, v4.1.1.

**Comment by kholland-intel** [comment]
It appears that v4.1.1 introduces differences in two of the config files that SOS cares about: ompi_check_ucx.m4 and opal_check_pmi.m4. The changes consist of about ~35 and ~300 lines of code, respectively.

**Comment by kholland-intel** [comment]
Of the changes introduced in ompi v4.1.1, we have decided to only incorporate the updates to ompi_check_ucx.m4 into SOS for now. Bringing in the PMIx config file (opal_check_pmi.m4) led to errors/failures in the SOS test suite.

**Comment by davidozog** [comment]
I believe we can close this.  We see upstream changes to PMI/PMIx configury, but will revisit incorporating those in future releases of SOS (this process is included in the release checklist).
