### ISSUE TITLE
Number of PEs in SHMEM_TEAM_SHARED always returns 1

### ISSUE THREAD

**Issue by rzambre** [Sandia-OpenSHMEM/SOS#996]
I am new to OpenSHMEM, so forgive me if I am missing something obvious here.
My goal is to find the equivalent of `MPI_COMM_TYPE_SHARED` in OpenSHMEM. I believe it is `SHMEM_TEAM_SHARED`.

But when I run the following program with `oshrun -n 4 ./shmem_team_shared` on a single node, I don't seen an expected output.

```
#include <stdio.h>
#include <shmem.h>

int main()
{
    int my_world_pe, my_shared_pe;
    int num_world_pes, num_shared_pes;
    void *pe_ptr_0, *pe_ptr_1, *pe_ptr_2, *pe_ptr_3;

    shmem_init();

    my_world_pe = shmem_team_my_pe(SHMEM_TEAM_WORLD);
    my_shared_pe = shmem_team_my_pe(SHMEM_TEAM_SHARED);

    num_world_pes = shmem_team_n_pes(SHMEM_TEAM_WORLD);
    num_shared_pes = shmem_team_n_pes(SHMEM_TEAM_SHARED);

    shmem_ptr(pe_ptr_0, 0);
    shmem_ptr(pe_ptr_1, 1);
    shmem_ptr(pe_ptr_2, 2);
    shmem_ptr(pe_ptr_3, 3);

    printf("PE %d of %d: %d PEs on my node; my rank here is %d; 0: %p, 1: %p, 2: %p, 3: %p\n",
            my_world_pe, num_world_pes, num_shared_pes, my_shared_pe, pe_ptr_0, pe_ptr_1, pe_ptr_2, pe_ptr_3);    
    shmem_finalize();

    return 0;
}
```
Instead, I see the following output. I would've expected to see `4 PEs on my node`, and valid pointers for all 4 PEs.
```
PE 0 of 4: 1 PEs on my node; my rank here is 0; 0: 0x400a10, 1: 0x400830, 2: 0x7ffef755b930, 3: (nil)
PE 2 of 4: 1 PEs on my node; my rank here is 2; 0: 0x400a10, 1: 0x400830, 2: 0x7ffcff552250, 3: (nil)
PE 3 of 4: 1 PEs on my node; my rank here is 3; 0: 0x400a10, 1: 0x400830, 2: 0x7ffd0a5d11e0, 3: (nil)
PE 1 of 4: 1 PEs on my node; my rank here is 1; 0: 0x400a10, 1: 0x400830, 2: 0x7ffeb15f5970, 3: (nil)
```
This is how I configured SOS: `../configure --prefix=/path/to/SOS/install --with-ucx=/path/to/ucx/install --enable-pmi-simple --with-cma`

From my debugging, I suspect the issue lies here: https://github.com/Sandia-OpenSHMEM/SOS/blob/master/src/shmem_remote_pointer.h#L23-L43

Would TEAM_SHARED work only with xpmem?

**Comment by davidozog** [comment]
Hi @rzambre - thanks for the great question.

Yes - only by enabling XPMEM will `SHMEM_TEAM_SHARED` do what you're looking for...  If you have root permissions on your system, it's relatively straight-forward to setup XPMEM (e.g., [see here](https://github.com/Sandia-OpenSHMEM/SOS/blob/master/.travis.yml#L265)).

We do have an experimental branch that includes 2 pre-defined teams, `SHMEMX_TEAM_HOST`, which consists of all PEs sharing the same hostname, and `SHMEMX_TEAM_LEADER`, which consists of 1 unique PE from each host.  It might be fairly easy to merge that into the master branch if it's useful for you?

**Comment by rzambre** [comment]
Hi @davidozog, thanks for the pointer. I will try out the XPMEM setup.

A follow-up question -- if I am understanding correctly, wouldn't `SHMEMX_TEAM_HOST` be exactly `SHMEM_TEAM_SHARED`? I am curious if there are cases of `SHMEM_TEAM_SHARED` that wouldn't be covered by `SHMEMX_TEAM_HOST`.

**Comment by davidozog** [comment]
They are very similar, but not the exact same...

`SHMEM_TEAM_SHARED` is defined in terms of whether or not `shmem_ptr` returns a non-null pointer, which is not the case with `SHMEMX_TEAM_HOST`.  You should be able to do loads/stores to other PEs on `SHMEM_TEAM_SHARED`, but it still may be advantages to do RMA's/AMO's on `SHMEMX_TEAM_HOST` over the network loopback interface, for example. 

I don't believe you can do inter-process loads/stores over CMA, but please correct me if I'm wrong...  but now I'm very surprised by your output above - shouldn't each PE print NULL for all PEs except for itself?

Oh, you may be using `shmem_ptr` incorrectly.  It _returns_ the address to which you can do loads and stores.  The `pe_ptr_*` pointers should point to something that was allocated with `shmem_malloc` or something like that, right?

**Comment by rzambre** [comment]
Thanks for the clarification. It makes sense.

> Oh, you may be using shmem_ptr incorrectly.
Yes, you are right. Thanks for catching my rookie mistake. If I do a `shmem_malloc` and use `shmem_ptr` correctly, I see the expected output: each PE prints NULL for all PEs except for itself.

**Comment by rzambre** [comment]
Just tried out my toy program with an SOS-with-xpmem build and I see the expected results with TEAM_SHARED.

Thanks for the quick response! Closing this issue.
